// file: client/src/utils/moodQuotes.ts

export const moodQuotes: Record<string, string[]> = {
  happy: [
    "I'm feeling bubbly today!",
    "The stars are extra sparkly",
    "You make my tentacles tingle with joy!",
    "Jellyfish are fun to bounce on!",
    "Why yes, I know Crush the turtle!",
    "Just a squid in a cosmic sea of happiness!",
  ],
  tired: [
    "Nap time...",
    "Too many bubbles... need rest...",
    "Energy levels low. Send snacks.",
    "So... much... swimming...",
    "Just a little inked out...",
    "Doubts... Blake... doubts...",
  ],
  focused: [
    "Engaging focus mode",
    "Time to conquer the task sea!",
    "Zero distractions. Full swim ahead.",
    "Just keep swimming, just keep swimming...",
    "One bubble, two bubble, INK SPOT!",
  ],
  playful: [
    "Wanna play tag in the stars?",
    "Bet you can’t catch me!",
    "Let’s chase some moon jellyfish!",
    "Ink squirt! Gotcha!",
    "Go Fish? GO FISH!",
  ],
  sad: [
    "My glow's a little dim today...",
    "Feeling... a bit inked out.",
    "Hug me with your thoughts",
    "Even squids have off days...",
    "Just a little lost in the cosmic sea...",
    "Floating in the void, floating in the void...",
  ],
  idle: [
    "I'm just floating...",
    "What a peaceful orbit",
    "Do squids dream of electric jellyfish?",
    "... how many tentacles does it take to change a lightbulb?",
    "I don't know, do squids live in space?",
  ],
  anxious: [
    "Are the space currents okay?",
    "Something feels... wobbly.",
    "Are you clicking the right button?",
    "Is the universe aligned?",
    "I hope the stars are in my favor today...",
    "Is it just me, or is the void getting closer?",
    "Black holes... they really need a better name.",
  ],
  inspired: [
    "A cosmic idea just sparked!",
    "Let’s create something stellar!",
    "The universe is my canvas!",
    "Ink flows like inspiration!",
    "Ideas are like stars, infinite and bright!",
    "I bet I can ink a masterpiece!",
  ],
  angry: [
    "Ink incoming...!",
    "Stay out of my bubble!",
    "I am not an octopus!",
    "Tentacles ready for battle!",
    "You wouldn't like me when I'm inked!",
    "I’m not mad, just tentacly frustrated!",
  ],
};
